import { qlFn, parseType } from "./index.ts";

export const operations = {
  and: qlFn.create("AND"),
  or: qlFn.create("OR"),
  is: qlFn.create("IS"),
  isNot: qlFn.create("IS NOT"),
  in: qlFn.create("IN"),
  notIn: qlFn.create("NOT IN"),
  contains: qlFn.create("CONTAINS"),
  containsNot: qlFn.create("CONTAINSNOT"),
  containsAll: qlFn.create("CONTAINSALL"),
  containsAny: qlFn.create("CONTAINSANY"),
  containsNone: qlFn.create("CONTAINSNONE"),
  inside: qlFn.create("INSIDE"),
  notInside: qlFn.create("NOTINSIDE"),
  allInside: qlFn.create("ALLINSIDE"),
  anyInside: qlFn.create("ANYINSIDE"),
  noneInside: qlFn.create("NONEINSIDE"),
  intersects: qlFn.create("INTERSECTS"),
  lt: (val: any) => qlFn.create(`< ${parseType(val)}`),
  lte: (val: any) => qlFn.create(`<= ${parseType(val)}`),
  gt: (val: any) => qlFn.create(`> ${parseType(val)}`),
  gte: (val: any) => qlFn.create(`>= ${parseType(val)}`),
  ne: (val: any) => qlFn.create(`!= ${parseType(val)}`),
  eq: (val: any) => qlFn.create(`= ${parseType(val)}`),
  "@@": qlFn.create("@@"),
  "??": qlFn.create("??"),
  "?:": qlFn.create("?:"),
  "=": qlFn.create("="),
  "!=": qlFn.create("!="),
  "==": qlFn.create("=="),
  "?=": qlFn.create("?="),
  "*=": qlFn.create("*="),
  "~": qlFn.create("~"),
  "!~": qlFn.create("!~"),
  "?~": qlFn.create("?~"),
  "*~": qlFn.create("*~"),
  "<": qlFn.create("<"),
  "<=": qlFn.create("<="),
  ">": qlFn.create(">"),
  ">=": qlFn.create(">="),
  "+": qlFn.create("+"),
  "-": qlFn.create("-"),
  "*": qlFn.create("*"),
  "/": qlFn.create("/"),
  "**": qlFn.create("**"),
}